### ISSUE TITLE
Version 1.2.0 roadmap

### ISSUE THREAD

**Issue by firstred** [firstred/postnl-api-php#22]
Not all services seem to work with version 1.x.x. A lot of work has been put into creating version 2, but in the end, most of the experiments that were part of the new version turned out to be a bad idea.

Not applying all the changes from the 2.0.0 pull request actually has its advantages. Backward-compatibility, keeping the namespace, no need for Symfony Component(s) overhead (or creating dependency injection containers) are a few examples.
The SOAP-API still seems to be available for the foreseeable future, so it might be a good idea to just make the dependency on Sabre XML optional, rather than removing SOAP support altogether.

Taking the best bits of v2 should also be possible. Think of PSR-17 support (to easily support HTTP clients other than Guzzle), updating the services and probably a few more. ~~The new services that were going to be part of v2 turned out to be untestable and therefore unsuitable to be added to this library.~~ All except the checkout service work with v1.2.0 now.
Thanks to @janwilletje, support for the new Shipping Webservice can be added as well. Thanks a lot for your contribution!

I am not sure if the new Checkout Webservice is a good idea. I have tested this service myself and found that it was rather limited as opposed to just calling the three web services (locations + timeframes + delivery date) simultaneously. It may be a good candidate for v1.3.0, though.

With that said, I am going to try to compile a list of changes to be added to v1.2.0. Let's start with:

`v1.2.0-alpha.0`
- [x] Redirecting disabled legacy SOAP API => new SOAP API
- [x] Shipping web service
- [x] Making Sabre / XML optional
- [x] Remove dependencies on `guzzlehttp/promises` and `guzzlehttp/psr7`
- [x] Gather all hot patches I have applied on production and merge them into this library
- [x] HTTPlug for HTTP client + PSR-17 libs discovery
- [x] Migrate to the Labeling web service v2.2 (Jan 25, 2019)
- [x] Migrate to the Confirming web service v2.0 (Jan 25, 2019)

`v1.2.0-alpha.x`
- [x] REST fixes
- [x] ~~Use JSON Schema to verify REST responses~~ too ambitious
- [x] Optional phone number formatting (for pakketautomaten)
- [x] Support PHP 8
- [x] Support International Mail & Packets
- [x] Making it future-proof: support Guzzle PSR-7 v2
- ~~Support single-request multicollo shipments~~ Not enough information -- postponed
- [x] Making it future-proof: remove hard dependency on sabre/xml (seamlessly switch to REST)
- [x] Support `psr/cache` v2 and v3

`v1.2.0-beta.x`
- [x] Restore and fix tests
- [x] Update documentation

**Comment by firstred** [comment]
Added "Use XSD and JSON Schema to verify both resp. SOAP and REST responses"

**Comment by stonjohnsson** [comment]
Is there an update available for 1.2.0? We need this for PostNL Labeling API (2.2) to create international shipment labels.

**Comment by firstred** [comment]
Still working on it, sorry for the delay.

**Comment by firstred** [comment]
Meanwhile, I made a quick release to test the update: https://github.com/firstred/postnl-api-php/releases/tag/v1.2.0-alpha.1

If you're okay with lowering the [min stability requirement](https://getcomposer.org/doc/04-schema.md#minimum-stability) in `composer.json` then you're able to use the new release straight away.

**Comment by firstred** [comment]
Just updated the roadmap.

**Comment by firstred** [comment]
Version 1.2.0 has been released!
